version: '3.9'
services:
    janus:
        image: atyenoria/janus-webrtc-gateway-docker
        network_mode: host
        volumes:
            - type: bind
              source: ./janus/conf/janus.plugin.videoroom.jcfg
              target: /usr/local/etc/janus/janus.plugin.videoroom.jcfg
        depends_on:
            - nginx
    nginx:
        image: alfg/nginx-rtmp
        ports:
            - '1935:1935'
            - '8080:80'
            - target: 7500
              published: 7500
              protocol: udp
            - target: 7000
              published: 7000
              protocol: udp
        volumes:
            - type: bind
              source: ./videoroom
              target: /var/www/pub-sub
            - type: bind
              source: ./hls/nginx.conf
              target: /etc/nginx/nginx.conf.template
            - type: bind
              source: ./hls/janus.sdp
              target: /janus.sdp
